--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/SchematicPlots
projects:
  SchematicPlots:
    icon: "icon.png"
    path: ""
    libs:
      - src: Falkirks/spoondetector/spoondetector
        version: ^0.0.0
      - src: BlockHorizons/libschematic/BlockHorizons/libschematic
        version: ^0.0.0
...